apiVersion: histograph.ai/v1
kind: ModelDeployment
metadata:
  name: mobile-money-fraud-production
spec:
  environment: production
  model:
    name: mobile-money-fraud-detection
    task: binary_classification
    positiveClass: fraud
    positiveActual: 1
    datahubModelUrn: urn:li:mlModel:(urn:li:dataPlatform:mlflow,mobile-money-fraud-detection,PROD)
  runtime:
    provider: reference
    endpoint: http://runtime:8100
  interface:
    inputSchema:
      path: ../schemas/mobile-money-fraud-input.schema.json
    outputSchema:
      path: ../schemas/mobile-money-fraud-output.schema.json
    examples:
      path: ../examples/mobile-money-fraud.yaml
  stable:
    version: v1
    artifact: demo/artifacts/mobile_money_fraud.joblib
    configuration:
      decisionThreshold: 0.8247828532693404
    trafficPercentage: 100.0
  candidate:
    version: v2
    artifact: demo/artifacts/mobile_money_fraud.joblib
    configuration:
      decisionThreshold: 0.99
    trafficPercentage: 0.0
  features:
  - name: mobile-money-amount-feature
    assetUrn: urn:li:mlFeature:(mobile_money_transaction_features,amount)
    inputFeature: amount
    version: v1
    configuration:
      scaleMultiplier: 1
