"""create control plane schema

Revision ID: fdfa1cec5187
Revises:
Create Date: 2026-08-05 22:18:37.156372
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "fdfa1cec5187"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("external_subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("external_subject", name=op.f("uq_users_external_subject")),
    )
    op.create_table(
        "github_installations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("installation_id", sa.BigInteger(), nullable=False),
        sa.Column("account_login", sa.String(length=255), nullable=False),
        sa.Column("account_type", sa.String(length=40), nullable=False),
        sa.Column("repository_selection", sa.String(length=40), nullable=False),
        sa.Column(
            "permissions_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_github_installations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_github_installations")),
        sa.UniqueConstraint(
            "installation_id", name=op.f("uq_github_installations_installation_id")
        ),
    )
    op.create_index(
        op.f("ix_github_installations_organization_id"),
        "github_installations",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "memberships",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "admin",
                "engineer",
                "agent_owner",
                "reviewer",
                "observer",
                name="membership_role",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memberships_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint(
            "organization_id", "user_id", name=op.f("uq_memberships_organization_id")
        ),
    )
    op.create_index(
        "ix_memberships_user_organization",
        "memberships",
        ["user_id", "organization_id"],
        unique=False,
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column(
            "environment",
            sa.Enum("development", "staging", "production", name="project_environment"),
            nullable=False,
        ),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column("max_concurrent_runs", sa.Integer(), nullable=False),
        sa.Column(
            "default_trigger_policy_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_projects_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("organization_id", "slug", name=op.f("uq_projects_organization_id")),
    )
    op.create_index(
        op.f("ix_projects_organization_id"), "projects", ["organization_id"], unique=False
    )
    op.create_table(
        "agent_targets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("adapter_type", sa.String(length=80), nullable=False),
        sa.Column("base_url", sa.String(length=2048), nullable=False),
        sa.Column("engine_name", sa.String(length=255), nullable=False),
        sa.Column("encrypted_credentials", sa.Text(), nullable=True),
        sa.Column(
            "secret_location",
            sa.Enum("managed", "private_runner", name="agent_secret_location"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "verifying",
                "ready",
                "degraded",
                "failed",
                "disabled",
                name="agent_target_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "capabilities_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("prompt_fingerprint", sa.String(length=128), nullable=True),
        sa.Column(
            "model_identifiers_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_agent_targets_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_agent_targets_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_targets")),
        sa.UniqueConstraint(
            "project_id", "name", "version", name=op.f("uq_agent_targets_project_id")
        ),
    )
    op.create_index(
        op.f("ix_agent_targets_organization_id"), "agent_targets", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_targets_project_id"), "agent_targets", ["project_id"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("actor_type", sa.String(length=40), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=160), nullable=False),
        sa.Column("target_type", sa.String(length=120), nullable=False),
        sa.Column("target_id", sa.String(length=255), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("source_ip", sa.String(length=64), nullable=True),
        sa.Column("before_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("after_fingerprint", sa.String(length=64), nullable=True),
        sa.Column(
            "details_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_audit_events_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        op.f("ix_audit_events_organization_id"), "audit_events", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_project_id"), "audit_events", ["project_id"], unique=False
    )
    op.create_index(
        "ix_audit_events_scope_created",
        "audit_events",
        ["organization_id", "project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "datahub_connections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("mode", sa.String(length=40), nullable=False),
        sa.Column("endpoint_url", sa.String(length=2048), nullable=False),
        sa.Column("mcp_url", sa.String(length=2048), nullable=False),
        sa.Column("deployment_id", sa.String(length=255), nullable=True),
        sa.Column("encrypted_credentials", sa.Text(), nullable=True),
        sa.Column(
            "secret_location",
            sa.Enum("managed", "private_runner", name="datahub_secret_location"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "verifying",
                "ready",
                "degraded",
                "failed",
                "disabled",
                name="datahub_connection_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "capabilities_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_datahub_connections_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_datahub_connections_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_datahub_connections")),
        sa.UniqueConstraint(
            "project_id", "version", name=op.f("uq_datahub_connections_project_id")
        ),
    )
    op.create_index(
        op.f("ix_datahub_connections_organization_id"),
        "datahub_connections",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_datahub_connections_project_active",
        "datahub_connections",
        ["project_id", "active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_datahub_connections_project_id"),
        "datahub_connections",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "repository_connections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("github_installation_id", sa.String(length=36), nullable=False),
        sa.Column("repository_id", sa.BigInteger(), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=520), nullable=False),
        sa.Column("default_branch", sa.String(length=255), nullable=False),
        sa.Column(
            "configuration_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["github_installation_id"],
            ["github_installations.id"],
            name=op.f("fk_repository_connections_github_installation_id_github_installations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_repository_connections_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_repository_connections_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repository_connections")),
        sa.UniqueConstraint(
            "project_id", "repository_id", name=op.f("uq_repository_connections_project_id")
        ),
    )
    op.create_index(
        "ix_repository_connections_installation_repo",
        "repository_connections",
        ["github_installation_id", "repository_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_repository_connections_organization_id"),
        "repository_connections",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_repository_connections_project_id"),
        "repository_connections",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "runner_pools",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("mode", sa.String(length=40), nullable=False),
        sa.Column(
            "required_capabilities_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_runner_pools_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_runner_pools_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runner_pools")),
        sa.UniqueConstraint("project_id", "name", name=op.f("uq_runner_pools_project_id")),
    )
    op.create_index(
        op.f("ix_runner_pools_organization_id"), "runner_pools", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_runner_pools_project_id"), "runner_pools", ["project_id"], unique=False
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column(
            "trigger_type",
            sa.Enum(
                "manual",
                "api",
                "schedule",
                "github_pull_request",
                "github_push",
                "datahub_event",
                name="run_trigger_type",
            ),
            nullable=False,
        ),
        sa.Column("trigger_reference", sa.String(length=1024), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("requested_by", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "planning",
                "action_required",
                "executing",
                "evaluating",
                "diagnosing",
                "reporting",
                "passed",
                "failed",
                "warning",
                "error",
                "cancelled",
                "timed_out",
                name="run_status",
            ),
            nullable=False,
        ),
        sa.Column("workflow_id", sa.String(length=255), nullable=True),
        sa.Column("configuration_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "selection_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "impact_plan_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "report_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("planned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_by_run_id", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_runs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_runs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_run_id"],
            ["runs.id"],
            name=op.f("fk_runs_superseded_by_run_id_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
        sa.UniqueConstraint(
            "organization_id", "project_id", "idempotency_key", name=op.f("uq_runs_organization_id")
        ),
        sa.UniqueConstraint("workflow_id", name=op.f("uq_runs_workflow_id")),
    )
    op.create_index(op.f("ix_runs_organization_id"), "runs", ["organization_id"], unique=False)
    op.create_index(op.f("ix_runs_project_id"), "runs", ["project_id"], unique=False)
    op.create_index(
        "ix_runs_project_status_created",
        "runs",
        ["project_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "service_identities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("token_prefix", sa.String(length=24), nullable=False),
        sa.Column("token_digest", sa.String(length=64), nullable=False),
        sa.Column(
            "scopes_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_service_identities_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_service_identities_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service_identities")),
    )
    op.create_index(
        op.f("ix_service_identities_organization_id"),
        "service_identities",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_identities_project_id"), "service_identities", ["project_id"], unique=False
    )
    op.create_index(
        "ix_service_identities_token_digest", "service_identities", ["token_digest"], unique=True
    )
    op.create_table(
        "test_suites",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_test_suites_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_test_suites_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_suites")),
        sa.UniqueConstraint("project_id", "slug", name=op.f("uq_test_suites_project_id")),
    )
    op.create_index(
        op.f("ix_test_suites_organization_id"), "test_suites", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_test_suites_project_id"), "test_suites", ["project_id"], unique=False)
    op.create_table(
        "impact_plans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("risk_level", sa.String(length=40), nullable=False),
        sa.Column(
            "plan_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("selection_policy_version", sa.String(length=80), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_impact_plans_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_impact_plans_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_impact_plans_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_impact_plans")),
        sa.UniqueConstraint("run_id", name=op.f("uq_impact_plans_run_id")),
    )
    op.create_index(
        op.f("ix_impact_plans_organization_id"), "impact_plans", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_impact_plans_project_id"), "impact_plans", ["project_id"], unique=False
    )
    op.create_table(
        "metadata_event_receipts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("datahub_connection_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=120), nullable=False),
        sa.Column("idempotency_key", sa.String(length=512), nullable=False),
        sa.Column("entity_urn", sa.String(length=1024), nullable=False),
        sa.Column("event_type", sa.String(length=160), nullable=False),
        sa.Column("aspect_name", sa.String(length=255), nullable=True),
        sa.Column("aspect_version", sa.Integer(), nullable=True),
        sa.Column("cursor", sa.String(length=512), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "payload_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "processing",
                "processed",
                "ignored",
                "failed",
                name="metadata_receipt_status",
            ),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["datahub_connection_id"],
            ["datahub_connections.id"],
            name=op.f("fk_metadata_event_receipts_datahub_connection_id_datahub_connections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_metadata_event_receipts_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_metadata_event_receipts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_metadata_event_receipts_run_id_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metadata_event_receipts")),
        sa.UniqueConstraint(
            "organization_id",
            "source",
            "idempotency_key",
            name=op.f("uq_metadata_event_receipts_organization_id"),
        ),
    )
    op.create_index(
        op.f("ix_metadata_event_receipts_organization_id"),
        "metadata_event_receipts",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_event_receipts_project_id"),
        "metadata_event_receipts",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "ix_metadata_events_project_status",
        "metadata_event_receipts",
        ["project_id", "status", "created_at"],
        unique=False,
    )
    op.create_table(
        "protected_questions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("suite_id", sa.String(length=36), nullable=False),
        sa.Column("stable_key", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("criticality", sa.String(length=40), nullable=False),
        sa.Column("owner_reference", sa.String(length=255), nullable=True),
        sa.Column("active_version_id", sa.String(length=36), nullable=True),
        sa.Column("active_baseline_id", sa.String(length=36), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_protected_questions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_protected_questions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["suite_id"],
            ["test_suites.id"],
            name=op.f("fk_protected_questions_suite_id_test_suites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_protected_questions")),
        sa.UniqueConstraint(
            "project_id", "stable_key", name=op.f("uq_protected_questions_project_id")
        ),
    )
    op.create_index(
        op.f("ix_protected_questions_organization_id"),
        "protected_questions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_protected_questions_project_id"),
        "protected_questions",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_protected_questions_suite_id"), "protected_questions", ["suite_id"], unique=False
    )
    op.create_table(
        "runners",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("runner_pool_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column(
            "capabilities_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_runners_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_runners_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["runner_pool_id"],
            ["runner_pools.id"],
            name=op.f("fk_runners_runner_pool_id_runner_pools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runners")),
    )
    op.create_index(
        op.f("ix_runners_organization_id"), "runners", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_runners_project_id"), "runners", ["project_id"], unique=False)
    op.create_index(op.f("ix_runners_runner_pool_id"), "runners", ["runner_pool_id"], unique=False)
    op.create_table(
        "webhook_receipts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=True),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("delivery_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=160), nullable=False),
        sa.Column("action", sa.String(length=160), nullable=True),
        sa.Column("signature_valid", sa.Boolean(), nullable=False),
        sa.Column(
            "payload_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "processing",
                "processed",
                "ignored",
                "failed",
                name="webhook_receipt_status",
            ),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_webhook_receipts_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_webhook_receipts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_webhook_receipts_run_id_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_receipts")),
        sa.UniqueConstraint("source", "delivery_id", name=op.f("uq_webhook_receipts_source")),
    )
    op.create_index(
        op.f("ix_webhook_receipts_organization_id"),
        "webhook_receipts",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_receipts_project_id"), "webhook_receipts", ["project_id"], unique=False
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("protected_question_id", sa.String(length=36), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("status", sa.Enum("open", "resolved", name="incident_status"), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("resource_urn", sa.String(length=1024), nullable=False),
        sa.Column("first_run_id", sa.String(length=36), nullable=False),
        sa.Column("latest_run_id", sa.String(length=36), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("consecutive_success_count", sa.Integer(), nullable=False),
        sa.Column("datahub_incident_urn", sa.String(length=1024), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["first_run_id"],
            ["runs.id"],
            name=op.f("fk_incidents_first_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["latest_run_id"],
            ["runs.id"],
            name=op.f("fk_incidents_latest_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_incidents_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_incidents_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["protected_question_id"],
            ["protected_questions.id"],
            name=op.f("fk_incidents_protected_question_id_protected_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
        sa.UniqueConstraint(
            "organization_id",
            "project_id",
            "fingerprint",
            name=op.f("uq_incidents_organization_id"),
        ),
    )
    op.create_index(
        op.f("ix_incidents_organization_id"), "incidents", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_incidents_project_id"), "incidents", ["project_id"], unique=False)
    op.create_table(
        "run_test_selections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("protected_question_id", sa.String(length=36), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "evidence_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_run_test_selections_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_run_test_selections_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["protected_question_id"],
            ["protected_questions.id"],
            name=op.f("fk_run_test_selections_protected_question_id_protected_questions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_run_test_selections_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_test_selections")),
        sa.UniqueConstraint(
            "run_id", "protected_question_id", name=op.f("uq_run_test_selections_run_id")
        ),
    )
    op.create_index(
        op.f("ix_run_test_selections_organization_id"),
        "run_test_selections",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_run_test_selections_project_id"),
        "run_test_selections",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_run_test_selections_run_id"), "run_test_selections", ["run_id"], unique=False
    )
    op.create_table(
        "schedules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("suite_id", sa.String(length=36), nullable=True),
        sa.Column("protected_question_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("cron_expression", sa.String(length=160), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column(
            "concurrency_policy",
            sa.Enum("skip", "queue", "replace", name="schedule_concurrency"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("temporal_schedule_id", sa.String(length=255), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_schedules_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_schedules_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["protected_question_id"],
            ["protected_questions.id"],
            name=op.f("fk_schedules_protected_question_id_protected_questions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["suite_id"],
            ["test_suites.id"],
            name=op.f("fk_schedules_suite_id_test_suites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedules")),
        sa.UniqueConstraint("project_id", "name", name=op.f("uq_schedules_project_id")),
        sa.UniqueConstraint("temporal_schedule_id", name=op.f("uq_schedules_temporal_schedule_id")),
    )
    op.create_index(
        op.f("ix_schedules_organization_id"), "schedules", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_schedules_project_id"), "schedules", ["project_id"], unique=False)
    op.create_table(
        "test_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("protected_question_id", sa.String(length=36), nullable=False),
        sa.Column("agent_target_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "configuration_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_target_id"],
            ["agent_targets.id"],
            name=op.f("fk_test_versions_agent_target_id_agent_targets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_test_versions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_test_versions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["protected_question_id"],
            ["protected_questions.id"],
            name=op.f("fk_test_versions_protected_question_id_protected_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_versions")),
        sa.UniqueConstraint(
            "protected_question_id", "version", name=op.f("uq_test_versions_protected_question_id")
        ),
    )
    op.create_index(
        op.f("ix_test_versions_organization_id"), "test_versions", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_test_versions_project_id"), "test_versions", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_test_versions_protected_question_id"),
        "test_versions",
        ["protected_question_id"],
        unique=False,
    )
    op.create_table(
        "baseline_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("protected_question_id", sa.String(length=36), nullable=False),
        sa.Column("test_version_id", sa.String(length=36), nullable=False),
        sa.Column("source_execution_id", sa.String(length=36), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "approved", "superseded", name="baseline_status"),
            nullable=False,
        ),
        sa.Column(
            "evidence_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "assertions_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("environment_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approval_justification", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_baseline_versions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_baseline_versions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["protected_question_id"],
            ["protected_questions.id"],
            name=op.f("fk_baseline_versions_protected_question_id_protected_questions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["test_version_id"],
            ["test_versions.id"],
            name=op.f("fk_baseline_versions_test_version_id_test_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_baseline_versions")),
        sa.UniqueConstraint(
            "protected_question_id",
            "version",
            name=op.f("uq_baseline_versions_protected_question_id"),
        ),
    )
    op.create_index(
        op.f("ix_baseline_versions_organization_id"),
        "baseline_versions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_baseline_versions_project_id"), "baseline_versions", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_baseline_versions_protected_question_id"),
        "baseline_versions",
        ["protected_question_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_protected_questions_active_version_id_test_versions",
        "protected_questions",
        "test_versions",
        ["active_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_protected_questions_active_baseline_id_baseline_versions",
        "protected_questions",
        "baseline_versions",
        ["active_baseline_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "datahub_writebacks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("incident_id", sa.String(length=36), nullable=True),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("operation", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column(
            "request_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "response_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_datahub_writebacks_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_datahub_writebacks_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_datahub_writebacks_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_datahub_writebacks_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_datahub_writebacks")),
        sa.UniqueConstraint(
            "organization_id", "idempotency_key", name=op.f("uq_datahub_writebacks_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_datahub_writebacks_organization_id"),
        "datahub_writebacks",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_datahub_writebacks_project_id"), "datahub_writebacks", ["project_id"], unique=False
    )
    op.create_table(
        "baseline_dependencies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("baseline_version_id", sa.String(length=36), nullable=False),
        sa.Column("asset_urn", sa.String(length=1024), nullable=False),
        sa.Column("field_path", sa.String(length=512), nullable=False),
        sa.Column("dependency_type", sa.String(length=80), nullable=False),
        sa.Column("environment", sa.String(length=80), nullable=False),
        sa.Column(
            "evidence_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["baseline_version_id"],
            ["baseline_versions.id"],
            name=op.f("fk_baseline_dependencies_baseline_version_id_baseline_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_baseline_dependencies_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_baseline_dependencies_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_baseline_dependencies")),
        sa.UniqueConstraint(
            "baseline_version_id",
            "asset_urn",
            "field_path",
            "dependency_type",
            name=op.f("uq_baseline_dependencies_baseline_version_id"),
        ),
    )
    op.create_index(
        "ix_baseline_dependencies_asset",
        "baseline_dependencies",
        ["organization_id", "project_id", "asset_urn"],
        unique=False,
    )
    op.create_index(
        op.f("ix_baseline_dependencies_baseline_version_id"),
        "baseline_dependencies",
        ["baseline_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_baseline_dependencies_organization_id"),
        "baseline_dependencies",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_baseline_dependencies_project_id"),
        "baseline_dependencies",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "review_decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("baseline_version_id", sa.String(length=36), nullable=False),
        sa.Column("reviewer_reference", sa.String(length=255), nullable=False),
        sa.Column("decision", sa.String(length=40), nullable=False),
        sa.Column("justification", sa.Text(), nullable=False),
        sa.Column("before_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("after_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["baseline_version_id"],
            ["baseline_versions.id"],
            name=op.f("fk_review_decisions_baseline_version_id_baseline_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_review_decisions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_review_decisions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_decisions")),
    )
    op.create_index(
        op.f("ix_review_decisions_baseline_version_id"),
        "review_decisions",
        ["baseline_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_decisions_organization_id"),
        "review_decisions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_decisions_project_id"), "review_decisions", ["project_id"], unique=False
    )
    op.create_table(
        "test_executions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("protected_question_id", sa.String(length=36), nullable=False),
        sa.Column("test_version_id", sa.String(length=36), nullable=False),
        sa.Column("baseline_version_id", sa.String(length=36), nullable=True),
        sa.Column("agent_target_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "executing",
                "evaluating",
                "passed",
                "failed",
                "error",
                "cancelled",
                "timed_out",
                name="test_execution_status",
            ),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column(
            "evidence_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "evaluation_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_target_id"],
            ["agent_targets.id"],
            name=op.f("fk_test_executions_agent_target_id_agent_targets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["baseline_version_id"],
            ["baseline_versions.id"],
            name=op.f("fk_test_executions_baseline_version_id_baseline_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_test_executions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_test_executions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["protected_question_id"],
            ["protected_questions.id"],
            name=op.f("fk_test_executions_protected_question_id_protected_questions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_test_executions_run_id_runs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["test_version_id"],
            ["test_versions.id"],
            name=op.f("fk_test_executions_test_version_id_test_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_executions")),
        sa.UniqueConstraint(
            "run_id", "protected_question_id", name=op.f("uq_test_executions_run_id")
        ),
    )
    op.create_index(
        op.f("ix_test_executions_organization_id"),
        "test_executions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_test_executions_project_id"), "test_executions", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_test_executions_run_id"), "test_executions", ["run_id"], unique=False)
    op.create_table(
        "incident_occurrences",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("test_execution_id", sa.String(length=36), nullable=False),
        sa.Column("occurrence_type", sa.String(length=40), nullable=False),
        sa.Column(
            "evidence_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_incident_occurrences_incident_id_incidents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_incident_occurrences_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_incident_occurrences_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_incident_occurrences_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["test_execution_id"],
            ["test_executions.id"],
            name=op.f("fk_incident_occurrences_test_execution_id_test_executions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_occurrences")),
        sa.UniqueConstraint(
            "incident_id",
            "run_id",
            "test_execution_id",
            "occurrence_type",
            name=op.f("uq_incident_occurrences_incident_id"),
        ),
    )
    op.create_index(
        op.f("ix_incident_occurrences_incident_id"),
        "incident_occurrences",
        ["incident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incident_occurrences_organization_id"),
        "incident_occurrences",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incident_occurrences_project_id"),
        "incident_occurrences",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incident_occurrences_run_id"),
        "incident_occurrences",
        ["run_id"],
        unique=False,
    )
    op.create_table(
        "agent_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("test_execution_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("event_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "payload_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_agent_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_agent_events_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["test_execution_id"],
            ["test_executions.id"],
            name=op.f("fk_agent_events_test_execution_id_test_executions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_events")),
        sa.UniqueConstraint(
            "test_execution_id", "event_id", name="uq_agent_events_execution_event_id"
        ),
        sa.UniqueConstraint(
            "test_execution_id", "sequence", name="uq_agent_events_execution_sequence"
        ),
    )
    op.create_index(
        op.f("ix_agent_events_test_execution_id"),
        "agent_events",
        ["test_execution_id"],
        unique=False,
    )
    op.create_table(
        "artifact_references",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("test_execution_id", sa.String(length=36), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "agent_trace", "sql", "result_sample", "impact_plan", "report", name="artifact_kind"
            ),
            nullable=False,
        ),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_artifact_references_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_artifact_references_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_artifact_references_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["test_execution_id"],
            ["test_executions.id"],
            name=op.f("fk_artifact_references_test_execution_id_test_executions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifact_references")),
        sa.UniqueConstraint(
            "organization_id", "object_key", name=op.f("uq_artifact_references_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_artifact_references_run_id"), "artifact_references", ["run_id"], unique=False
    )
    op.create_table(
        "execution_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("test_execution_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "executing",
                "evaluating",
                "passed",
                "failed",
                "error",
                "cancelled",
                "timed_out",
                name="execution_attempt_status",
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_execution_attempts_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_execution_attempts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["test_execution_id"],
            ["test_executions.id"],
            name=op.f("fk_execution_attempts_test_execution_id_test_executions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_attempts")),
        sa.UniqueConstraint(
            "test_execution_id",
            "attempt_number",
            name=op.f("uq_execution_attempts_test_execution_id"),
        ),
    )
    op.create_index(
        op.f("ix_execution_attempts_test_execution_id"),
        "execution_attempts",
        ["test_execution_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_protected_questions_active_baseline_id_baseline_versions",
        "protected_questions",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_protected_questions_active_version_id_test_versions",
        "protected_questions",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_execution_attempts_test_execution_id"), table_name="execution_attempts")
    op.drop_table("execution_attempts")
    op.drop_index(op.f("ix_artifact_references_run_id"), table_name="artifact_references")
    op.drop_table("artifact_references")
    op.drop_index(op.f("ix_agent_events_test_execution_id"), table_name="agent_events")
    op.drop_table("agent_events")
    op.drop_index(op.f("ix_incident_occurrences_run_id"), table_name="incident_occurrences")
    op.drop_index(op.f("ix_incident_occurrences_project_id"), table_name="incident_occurrences")
    op.drop_index(
        op.f("ix_incident_occurrences_organization_id"), table_name="incident_occurrences"
    )
    op.drop_index(op.f("ix_incident_occurrences_incident_id"), table_name="incident_occurrences")
    op.drop_table("incident_occurrences")
    op.drop_index(op.f("ix_test_executions_run_id"), table_name="test_executions")
    op.drop_index(op.f("ix_test_executions_project_id"), table_name="test_executions")
    op.drop_index(op.f("ix_test_executions_organization_id"), table_name="test_executions")
    op.drop_table("test_executions")
    op.drop_index(op.f("ix_review_decisions_project_id"), table_name="review_decisions")
    op.drop_index(op.f("ix_review_decisions_organization_id"), table_name="review_decisions")
    op.drop_index(op.f("ix_review_decisions_baseline_version_id"), table_name="review_decisions")
    op.drop_table("review_decisions")
    op.drop_index(op.f("ix_baseline_dependencies_project_id"), table_name="baseline_dependencies")
    op.drop_index(
        op.f("ix_baseline_dependencies_organization_id"), table_name="baseline_dependencies"
    )
    op.drop_index(
        op.f("ix_baseline_dependencies_baseline_version_id"), table_name="baseline_dependencies"
    )
    op.drop_index("ix_baseline_dependencies_asset", table_name="baseline_dependencies")
    op.drop_table("baseline_dependencies")
    op.drop_index(op.f("ix_datahub_writebacks_project_id"), table_name="datahub_writebacks")
    op.drop_index(op.f("ix_datahub_writebacks_organization_id"), table_name="datahub_writebacks")
    op.drop_table("datahub_writebacks")
    op.drop_index(
        op.f("ix_baseline_versions_protected_question_id"), table_name="baseline_versions"
    )
    op.drop_index(op.f("ix_baseline_versions_project_id"), table_name="baseline_versions")
    op.drop_index(op.f("ix_baseline_versions_organization_id"), table_name="baseline_versions")
    op.drop_table("baseline_versions")
    op.drop_index(op.f("ix_test_versions_protected_question_id"), table_name="test_versions")
    op.drop_index(op.f("ix_test_versions_project_id"), table_name="test_versions")
    op.drop_index(op.f("ix_test_versions_organization_id"), table_name="test_versions")
    op.drop_table("test_versions")
    op.drop_index(op.f("ix_schedules_project_id"), table_name="schedules")
    op.drop_index(op.f("ix_schedules_organization_id"), table_name="schedules")
    op.drop_table("schedules")
    op.drop_index(op.f("ix_run_test_selections_run_id"), table_name="run_test_selections")
    op.drop_index(op.f("ix_run_test_selections_project_id"), table_name="run_test_selections")
    op.drop_index(op.f("ix_run_test_selections_organization_id"), table_name="run_test_selections")
    op.drop_table("run_test_selections")
    op.drop_index(op.f("ix_incidents_project_id"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_organization_id"), table_name="incidents")
    op.drop_table("incidents")
    op.drop_index(op.f("ix_webhook_receipts_project_id"), table_name="webhook_receipts")
    op.drop_index(op.f("ix_webhook_receipts_organization_id"), table_name="webhook_receipts")
    op.drop_table("webhook_receipts")
    op.drop_index(op.f("ix_runners_runner_pool_id"), table_name="runners")
    op.drop_index(op.f("ix_runners_project_id"), table_name="runners")
    op.drop_index(op.f("ix_runners_organization_id"), table_name="runners")
    op.drop_table("runners")
    op.drop_index(op.f("ix_protected_questions_suite_id"), table_name="protected_questions")
    op.drop_index(op.f("ix_protected_questions_project_id"), table_name="protected_questions")
    op.drop_index(op.f("ix_protected_questions_organization_id"), table_name="protected_questions")
    op.drop_table("protected_questions")
    op.drop_index("ix_metadata_events_project_status", table_name="metadata_event_receipts")
    op.drop_index(
        op.f("ix_metadata_event_receipts_project_id"), table_name="metadata_event_receipts"
    )
    op.drop_index(
        op.f("ix_metadata_event_receipts_organization_id"), table_name="metadata_event_receipts"
    )
    op.drop_table("metadata_event_receipts")
    op.drop_index(op.f("ix_impact_plans_project_id"), table_name="impact_plans")
    op.drop_index(op.f("ix_impact_plans_organization_id"), table_name="impact_plans")
    op.drop_table("impact_plans")
    op.drop_index(op.f("ix_test_suites_project_id"), table_name="test_suites")
    op.drop_index(op.f("ix_test_suites_organization_id"), table_name="test_suites")
    op.drop_table("test_suites")
    op.drop_index("ix_service_identities_token_digest", table_name="service_identities")
    op.drop_index(op.f("ix_service_identities_project_id"), table_name="service_identities")
    op.drop_index(op.f("ix_service_identities_organization_id"), table_name="service_identities")
    op.drop_table("service_identities")
    op.drop_index("ix_runs_project_status_created", table_name="runs")
    op.drop_index(op.f("ix_runs_project_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_organization_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_runner_pools_project_id"), table_name="runner_pools")
    op.drop_index(op.f("ix_runner_pools_organization_id"), table_name="runner_pools")
    op.drop_table("runner_pools")
    op.drop_index(op.f("ix_repository_connections_project_id"), table_name="repository_connections")
    op.drop_index(
        op.f("ix_repository_connections_organization_id"), table_name="repository_connections"
    )
    op.drop_index(
        "ix_repository_connections_installation_repo", table_name="repository_connections"
    )
    op.drop_table("repository_connections")
    op.drop_index(op.f("ix_datahub_connections_project_id"), table_name="datahub_connections")
    op.drop_index("ix_datahub_connections_project_active", table_name="datahub_connections")
    op.drop_index(op.f("ix_datahub_connections_organization_id"), table_name="datahub_connections")
    op.drop_table("datahub_connections")
    op.drop_index("ix_audit_events_scope_created", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_project_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_organization_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_agent_targets_project_id"), table_name="agent_targets")
    op.drop_index(op.f("ix_agent_targets_organization_id"), table_name="agent_targets")
    op.drop_table("agent_targets")
    op.drop_index(op.f("ix_projects_organization_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index("ix_memberships_user_organization", table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(
        op.f("ix_github_installations_organization_id"), table_name="github_installations"
    )
    op.drop_table("github_installations")
    op.drop_table("users")
    op.drop_table("organizations")
    bind = op.get_bind()
    for enum_name in (
        "execution_attempt_status",
        "artifact_kind",
        "test_execution_status",
        "schedule_concurrency",
        "incident_status",
        "webhook_receipt_status",
        "metadata_receipt_status",
        "run_status",
        "run_trigger_type",
        "baseline_status",
        "agent_target_status",
        "agent_secret_location",
        "datahub_connection_status",
        "datahub_secret_location",
        "project_environment",
        "membership_role",
    ):
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
